spring:
  application:
    name: portfolio

logging:
  level:
    org.springframework.web: debug

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}

githubclient:
  base-url: ${GITHUB_BASEURL}
  token:    ${GITHUB_TOKEN}
  user-agent: ${GITHUB_AGENT}
  username: ${GITHUB_USERNAME}

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${PORT:8080}
